# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'UniversalGames' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UniversalGames
  pod 'RxSwift', '~> 6.5'
  pod 'RxCocoa', '~> 6.5'
  pod 'Alamofire', '~> 5.8'
  pod 'SwiftyJSON', '~> 5.0'
  
  target 'UniversalGamesTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
